version: '3.8'

services:
  studentapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      spring.datasource.url: jdbc:mariadb://mariadb:3306/${DB_NAME}
      spring.datasource.username: ${DB_APPLICATION_USER}
      spring.datasource.password: ${DB_APPLICATION_PASSWORD}
    ports:
      - "8083:8083"
    expose:
      - "8083"
    depends_on:
      - mariadb
    networks:
      - default
  mariadb:
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: mariadb:latest
    container_name: studentdb
    ports:
      - "3310:3306"
    expose:
      - "3310"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_APPLICATION_USER}
      MYSQL_PASSWORD: ${DB_APPLICATION_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
